config/routes.rb
Rails.application.routes.draw do
  resources :regioncodes do
    resources :groups
  end

  resources :groups do
    resources :tourorders
  end

  resources :groups do
    resources :paxdatas 
  end

  resources :paxdatas do
    resources :groups 
  end

  resources :paxdatas do
    resources :tourorders
  end

  resources :tourorders do
    resources :paxdatas
  end

  root 'home#index'

  resources :dashboards

end

app/models/group.rb
class Group < ActiveRecord::Base
	self.table_name = "a03a3_group"
	belongs_to :regioncode
	has_many :tourorders
	has_many :paxdatas
	belongs_to :paxdata
end

app/models/order.rb
class Order < ActiveRecord::Base
	self.table_name = "a05b00_order"
end

app/models/paxdata.rb
class Paxdata < ActiveRecord::Base
	self.table_name = "a05b01_paxdata"
	belongs_to :group
	has_many :groups
	belongs_to :tourorder
	has_many :tourorders

	def self.dashboard

		data = Paxdata.select("Order_No, Pax_type, Pax_Gender, Tour_Code, Tour_Date").where("Pax_Gender = '女'")

		data.map{|d|[Group.find(d.Order_No).Region_Code, d.total]};
	end


end

app/models/regioncode.rb
class Regioncode < ActiveRecord::Base
	self.table_name = "a03a3_regioncode"
	has_many :groups
end

app/models/tourorder.rb
class Tourorder < ActiveRecord::Base
	self.table_name = "a05b01_tourorder"
	belongs_to :group
	belongs_to :paxdata
	has_many :paxdatas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def index
	end
	def show
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@startDate = '"';
		@endDate = "";
		@gender = "";
	end

	def dashboard
	end
end

app/controllers/paxdatas_controller.rb
class PaxdatasController < ApplicationController
	def index
		data = Paxdata.select("Order_No, Pax_type, Pax_Gender, Tour_Code, Tour_Date").where("Pax_Gender = @gender", Tour_Date: @startDate..@endDate)

	end
	def show

	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paxdatas_helper.rb
module PaxdatasHelper
end

app/views/dashboard/index.html.erb
<h2>結果</h2>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
<script type="text/javascript">
$(function () {

    $(document).ready(function () {

        // Build the chart
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Browser market shares at a specific website, 2014'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },
            series: [{
                type: 'pie',
                name: 'Browser share',
                data: [  <%= @data.to_json.html_safe %>
                ]
            }]                  
                ]
            }]
        });
    });
        });
    });

});
</script>
<%= data.map %>
<%= link_to "返回", root_path %>

app/views/dashboards/index.html.erb
<h2>結果</h2>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
<script type="text/javascript">
$(function () {

    $(document).ready(function () {

        // Build the chart
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Browser market shares at a specific website, 2014'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },
            series: [{
                type: 'pie',
                name: 'Browser share',
                data: [  <%= @data.to_json.html_safe %> 
                ]
            }]                  
                ]
            }]
        });
    });
        });
    });

});
</script>

<%= @data %>
<%= link_to "返回", root_path %>

app/views/home/dashboard.html.erb
<h2>結果</h2>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>

$(function () {

    $(document).ready(function () {

        // Build the chart
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: 'Browser market shares at a specific website, 2014'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },
            series: [{
                type: 'pie',
                name: 'Browser share',
                data: [  <%= @data.to_json.html_safe %>
                ]
            }]                  
                ]
            }]
        });
    });
        });
    });

});
<%= link_to "返回", root_path %>

app/views/home/index.html.erb
<h2 id = "h2">客戶忠誠度分析系統</h2>
<p>地區</p>
<div>
<%= collection_select( :Region_Code, :Region_Name, Regioncode.all, :Region_Code, :Region_Name)%>
</div>
<p>年度</p>
<div>
<%= select_tag(@startDate, options_for_select([['2007', '2007-01-01'], ['2008', '2008-01-01'], ['2009','2009-01-01'], ['2010','2010-01-01'], ['2011','2011-01-01']], '2007-01-01')) %>
</div>
<p>到</p>
<div>
<%= select_tag(@endDate, options_for_select([['2007', '2007-12-31'], ['2008','2008-12-31'], ['2009','2009-12-31'], ['2010','2010-12-31'], ['2011','2011-12-31']], '2007-12-31')) %>
</div>
<p>次數</p>
<div>
<%= select_tag(@gender, options_for_select([['男','男'], ['女', '女']], '女')) %>
</div>
<div>
<%= link_to "分析",  dashboards_path(@startDate, @endDate, gender) %>
</div>)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prefer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paxdatas/index.html.erb
<h2>結果</h2>

<%= link_to "返回", root_path %>